# Generated by Django 2.0.4 on 2018-04-28 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='poll',
            new_name='poll_id',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='question',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='created_by',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='choice',
            new_name='choice_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='poll',
            new_name='poll_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='voted_by',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll_id', 'user_id')},
        ),
    ]
